[project]
name = "toheute"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "gitpython>=3.1.44",
    "rich>=13.9.4",
    "ruff>=0.11.2",
]
